debug: false

# Database config
mysql:
  hostname: localhost
  port: 3306
  username: root
  password: 
  database: 21C
  delete: 30 #deletes logs older than X days. Set to 0 to never delete.
  
inventoryStorageType:
   death:
      enabled: true #saves inventories on player death
   restart:
      enabled: true #saves inventories on server restart