main: com.twentyonec.ItemsLogger.ItemsLogger
name: ItemsLogger
version: 1.0.1-Snapshot
author: 21C
api-version: "1.13"

permissions:
  itemslogger.log:
    description: Allows the player to get logged.
    default: op
  itemslogger.search:
     description: Command used to get list of logs.
     default: op
  itemslogger.view:
    description: Command used to view logged information
    default: op
 
commands:
   itemslogger:
     description: Displays list of logs
     usage: /itemslogger [player] <date> <cause> <index>
   openitemlog:
     description: Diplays log info
     usage: /openitemslog [player] [view|open] [date] [time] 