debug: false

# Database config
mysql:
  hostname: localhost
  port: 3306
  username: root
  password: 
  database: 21C
  
inventoryStorageType:
   death:
      enabled: true #saves inventories on player death
   restart:
      enabled: true #saves inventories on server restart