debug: false

# Database config
mysql:
  hostname: localhost
  port: 3306
  username: root
  password: 
  database: 21C
  delete: 30 #deletes logs older than X days. Set to 0 to never delete.
  
logTypes:
  death:
    enabled: true #logs player when they die
  restart:
    enabled: true #logs all players when server restarts
  join:
    enabled: true #logs player when the join the server
  quit:
    enabled: true #logs player when they quit the server